spring.datasource.url=jdbc:postgresql://localhost:5432/db_claim_service
spring.datasource.username=postgres
spring.datasource.password=password123

# MinIO Config
minio.endpoint=http://127.0.0.1:9000
minio.access-key=CFPIPnJlvTwhCdFol3mk
minio.secret-key=jgKbgftI6aty2hdbsseI1pDOnhcqsGwEnxitfmrH
minio.bucket-name=slss

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true